#!/bin/sh

LOGFILE=/opt/var/log/automatic.log
touch $LOGFILE

ENABLED=yes
PROCS=automatic
ARGS="-l $LOGFILE -a"
PREARGS=""
DESC=$PROCS
PATH=/Apps/opt/sbin:/Apps/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /Apps/opt/etc/init.d/rc.func
