#!/bin/sh

prefix="/Apps/opt"
PATH=${prefix}/bin:${prefix}/sbin:/sbin:/bin:/usr/sbin:/usr/bin

start() {
	echo "starting rtorrent..."
	screen -dmS rtorrent rtorrent -D -n -o import=/Apps/opt/etc/rtorrent/rtorrent.conf
	}

stop() {
	echo "stopping rtorrent..."
	 screen -S rtorrent -X quit
	}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
		restart)
		stop
		sleep 5
		start
		;;
	*)
		echo "Usage: $0 (start|stop|restart)"
		exit 1
		;;
esac

exit 0