#!/bin/sh

ENABLED=yes
PROCS=3proxy
ARGS="/Apps/opt/etc/3proxy/3proxy.cfg"
PREARGS=""
DESC=$PROCS
PATH=/Apps/opt/sbin:/Apps/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /Apps/opt/etc/init.d/rc.func
