#!/bin/sh

ENABLED=yes
PROCS=mediatomb
ARGS="-d -u root -g root -P /Apps/opt/var/run/mediatomb.pid -l /Apps/opt/var/log/mediatomb.log -m /Apps/opt/etc -f mediatomb -p 50501"
PREARGS=""
DESC=$PROCS
PATH=/Apps/opt/sbin:Apps/opt/bin:Apps/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /Apps/opt/etc/init.d/rc.func
