#!/bin/sh

ENABLED=yes
PROCS=mt-daapd
ARGS="-c /opt/etc/mt-daapd.conf"
PREARGS=""
DESC=$PROCS
PATH=/Apps/opt/sbin:/Apps/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /Apps/opt/etc/init.d/rc.func
