#!/bin/sh

ENABLED=yes
PROCS=sd-idle
ARGS="-i 600"
PREARGS=""
DESC=$PROCS
PATH=/Apps/opt/sbin:Apps/opt/bin:Apps/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /Apps/opt/etc/init.d/rc.func
